### ISSUE TITLE
Nuxt support??

### ISSUE THREAD

**Issue by ruslankonev** [ktsn/vue-designer#80]
@pi0, @ktsn, guys, how I can use it with Nuxt? I don't got a `./src` folder

**Comment by ruslankonev** [comment]
I have got a `Maximum call stack..` in footer component?
 
![image](https://user-images.githubusercontent.com/2588730/50046212-e358c300-00b0-11e9-855f-fa38a3923072.png)

```
<template>
  <footer class="footer">
    <div class="footer__wrapper">
      <a href="#" target="_blank" class="footer__item">
        © 1998 – {{ new Date().getFullYear() }} 
        <small class="-op">{{ $store.state.version }}</small>
      </a>
      <a href="mailto:" target="_blank" class="footer__item">
Support
      </a>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'Footer'
}
</script>


<style lang="sass" src="./styles.sass" scoped></style>
```

**Comment by pi0** [comment]
Hi. I would love to help more for getting this working. Will try to reproduce locally but @ruslankonev do you see any point that Nuxt could cause such loop?

**Comment by ruslankonev** [comment]
Thanks guys, I assumed that the Vue Designer would not get the data from the store, but did not expect that he would not execute the components.

@pi0, regarding `Maximum call stack...`, I'm not sure that the error was in the Vue Designer, I just trying to see how rendered footer component, and seeing nothing. I opened the console in the VSCode, and saw this error.

In any case, thank you guys for the new things that you create, it all helps to develop and extend the Vue/Nuxt architecture!
