### ISSUE TITLE
command 'extension.openVueDesigner' not found

### ISSUE THREAD

**Issue by Elfayer** [ktsn/vue-designer#81]
When I try to open the extension as described on the extension Details, I get the error: `command 'extension.openVueDesigner' not found`

### Reproduction
Ctrl + Shift + P ; `Open Vue Designer`
Note I can see the option, just I get an error when clicking it.

### Versions
Version: 1.30.1 (system setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.16299

**Comment by ktsn** [comment]
Do you try to run the command without opening any workspace? It is the possible case that I found.
The case should also be supported, I guess.
